### ISSUE TITLE
Cant install roverguage on Ubuntu 16.04.1 LTS

### ISSUE THREAD

**Issue by wheeliebin** [colinbourassa/rovergauge#13]
I've tried to install the .deb on Ubuntu 16.04.1 LTS, but it won't install due to 
requiring libqt5core5 - this is not installable as I think it has been replaced.

Output:

dpkg: dependency problems prevent configuration of rovergauge:
 rovergauge depends on libqt5core5 (>= 5.0.2); however:
  Package libqt5core5 is not installed.

So I tried to install libqt5core5 but couldn't

Output:

Package libqt5core5 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libqt5core5a:i386 libqt5core5a

I see someone has had a similar problem with memsgauge too..

Be very grateful if you could help with this - my Chimaera is sulking...

**Comment by colinbourassa** [comment]
I've built a .deb package for 0.8.6 that I think should fix this.

**Comment by wheeliebin** [comment]
Colin, thanks for that, yes it works fine.

**Comment by wheeliebin** [comment]
Thanks for fixing this - it runs fine now. Just waiting for the usb cable to see if I can get my Chimaera running.

BTW I see you say that the TTS connector is no longer available - I found this <http://www.ebay.co.uk/itm/131239350240> on eBay, it seems fine.

Chris
