### ISSUE TITLE
Can't report faults

### ISSUE THREAD

**Issue by tr7v8mike** [colinbourassa/rovergauge#14]
When I try to display the fault codes window, I receive the message that the fault codes cannot be displayed.  I have installed a Tornado EPROM.  Does that matter?

**Comment by stevesprint** [comment]
No, does NOT matter.
Not displaying the fault codes usually means you haven't established a successful connection with the 14CUX.
Good Luck, Steve Sprint

**Comment by nypple** [comment]
Hi, 
I'm probably missing something trivial - but can't find the .exe,
also tried to build with CMAKE (make-mingw-release.bat)  - but getting errors.

thanks for the software - looking for something like that for ages for my RRC.
Jonathan

**Comment by cgalpin** [comment]
It’s the windows zip file off of the download page. Currently it’s

https://github.com/colinbourassa/rovergauge/releases/download/0.9.3/rovergauge-0.9.3-Windows.zip

**Comment by nypple** [comment]
Thank you!
last question - is there an option to view the fuel level?
I want to replace the entire gauges cluster with a tablet using your software. 

Thanks!

**Comment by colinbourassa** [comment]
Sorry, the 14CUX does not get any input about the fuel level. That's handled by a separate circuit in the vehicle.
