### ISSUE TITLE
Install on Raspberry Pi Rasbian

### ISSUE THREAD

**Issue by PerLangkjaer** [colinbourassa/rovergauge#15]
Hello

I'm having trouble installing the libcomm and rovergauge on my Rpi
I have found a guide but can't seem to understand it.
Cound you please halp me?

This is the guide:

Download the latest source files from the github https://github.com/colinbourassa/rovergauge/releas... and extract tar.gz file to an appropriate place on your pi. Also download the libcomm14cux source https://github.com/colinbourassa/libcomm14cux/rele... and extract to another folder.
I am not sure if you need all of this QT5 stuff but it is what I installed as I initially thought I was going to have to compile from within QT:

sudo apt-get update
sudo apt-get upgrade
sudo apt-get install cmake
sudo apt-get install qtcreator
sudo apt-get install qt5-qmake
sudo apt-get install qt5-default

Create a folder in each of the extracted folders (libcomm14cux-2.1.1 & rovergauge-0.8.4) called something like 'build'.
cd to each of your two empty build folders and run the following from there (you may need to do libcomm14cux first?):

cmake ..
make
sudo make install

If all has gone well you should now have a working rovergauge executable in your rovergauge build folder!

If you want to record log files you need to add a folder called logs to your working directory.

Jessie seems to already have all the drivers for the FTDI cable installed.

Good luck!

**Comment by cgalpin** [comment]
What point did you get to? 

Assuming you installed the dependencies (using sudo apt-get ... commands) the steps should be something like

mkdir rovergauge
cd rovergauge

curl -L -O https://github.com/colinbourassa/libcomm14cux/archive/2.1.1.tar.gz
tar xzf 2.1.1.tar.gz
cd libcomm14cux-2.1.1
mkdir build
cd build
cmake ..
make
sudo make install

cd ../..
curl -L -O https://github.com/colinbourassa/rovergauge/archive/0.9.3.tar.gz
tar xzf 0.9.3.tar.gz
cd rovergauge-0.9.3
mkdir build
cd build
cmake ..
make
sudo make install

**Comment by PerLangkjaer** [comment]
Well that did the trick.
I when you put it in that way i understand what to do and got it installed.
Now i just need to test it.

Thank you so much, i'll get back with the next couple of questions later .
