### ISSUE TITLE
Startup in full screen

### ISSUE THREAD

**Issue by PerLangkjaer** [colinbourassa/rovergauge#16]
Hello

I've got it to start up at boot and hopefully working as well.
My issue is that it only starts in the middle of the screen at approx. 66% of the screen, thus showing the background on the sides.
I'm running it in a Raspberry Pi with Rasbian OS

![2018-01-03-105602_1824x984_scrot](https://user-images.githubusercontent.com/35040883/34517895-cc6f2f1e-f074-11e7-821a-7833f45fb73e.png)

**Comment by cgalpin** [comment]
I don't see an argument to start in full screen. I assume it runs properly once you fullscreen it though?

If it runs fine once you manually full screen it, I'd say you have 2 options

1. Ask Colin to add a commandline argument to start in fullscreen. Perhaps with a few votes he'd take the time to add this feature.
2. Just hack your build to do it. I have not tried it, but I suspect if you edit main.cpp, and change line 33 from

`w.show();`

to

`w.showFullScreen();`

it will start in fullscreen. Give it a try - it can't hurt.

hth
charles

**Comment by PerLangkjaer** [comment]
That did it, and then just make a new build.

I realised that when I said fullscreen i meant Maximized, and after testing the fullscreen option, I saw my own fault and corrected it.
 Thanks for your help.
