### ISSUE TITLE
Headless / Full Screen

### ISSUE THREAD

**Issue by mtempels** [colinbourassa/rovergauge#18]
Hi! 

Thanks for your brilliant piece of software.. Would it be possible to start rovergauge as a fullscreen / kiosk mode application in Linux? It would be nice to have the application start as the only application on the system on boot..

Thanks in advance!

Cheers

Matthijs Tempels

**Comment by mtempels** [comment]
Hi Colin,

Cool! I'm not so good at QT programming, but if there is anything I can help you with, I'm willing to help :-)

Cheers

Matthijs

**Comment by mtempels** [comment]
Wow! Noticed your commit! Will try it next week! Cheers!!

**Comment by colinbourassa** [comment]
At the moment I've only done minimal testing (and only on Linux, Ubuntu 18.04), but it seems to be working fine. If you're able to build/test the latest code and can give me feedback, that would be very helpful. Cheers!

**Comment by mtempels** [comment]
Hmm.. It seems we're running into a QT version problem.. Raspian runs QT 5.7.1 and apparently this version the QCommandLineOption class does not have all the required functions:

/root/rovergauge/main.cpp: In function ‘int main(int, char**)’:
/root/rovergauge/main.cpp:27:20: error: ‘class QCommandLineOption’ has no member named ‘setFlags’
   doublebaudOption.setFlags(QCommandLineOption::HiddenFromHelp);
                    ^~~~~~~~
/root/rovergauge/main.cpp:27:29: error: ‘HiddenFromHelp’ is not a member of ‘QCommandLineOption’
   doublebaudOption.setFlags(QCommandLineOption::HiddenFromHelp);
                             ^~~~~~~~~~~~~~~~~~
As far as I can see Ubuntu 18.04 comes with 5.9.1 of QT and the only way to get this in Raspian would be to compile it myself on the Pi.. (this will take a while ;-) )

Any ideas? Or should I just try to compile QT myself and make a nice tutorial in the process for your other Pi users ;-)

Cheers

Matthijs

**Comment by mtempels** [comment]
Right.. After compiling qt5.9.1 on my pi and linking rovergauge 0.1.0 against my own libs everything compiles and works :-)

login as pi -> `sudo -i`
`cd ~`

`git clone git://code.qt.io/qt/qtbase.git -b v5.9.1`
`cd qtbase`
`./configure -release -opensource -confirm-license -make libs -v`
`make` (Have a coffee.. or 2..)
`make install`
`cd ~`
make a file : `/etc/ld.so.conf.d/00-Qt5-5.9.1.conf` -> `/usr/local/Qt-5.9.1/lib`
`ldconfig`

this takes care of qt5.9.1

`git clone https://github.com/colinbourassa/rovergauge.git`
`cd rovergauge`
`mkdir build`
`cd build`
`export CMAKE_PREFIX_PATH="/usr/local/Qt-5.9.1/lib/cmake/"`
`cmake ..`
`make`
`make instal`l

this gives me a working rovergauge in /usr/local/bin/

Yay!
