### ISSUE TITLE
Connection stays Red

### ISSUE THREAD

**Issue by Alfa-Classic** [colinbourassa/rovergauge#19]
hi , i have bought an cable from ebay an uses you software , i had the ftdi already installed and it runs fine .
it sets the com port to Com2 and is shown in your softwre.
i turn on the ignition , cable already connected and i push the connect button , he connects me but the lamp stays red and he dont show me datas or let me read the faul codes.

Land Rover 3.9 V8 EFI 
Windows 10

**Comment by colinbourassa** [comment]
There are multiple possible causes for this:
* Improperly built cable (i.e. not using a 5V TTL serial chip, mis-wired pins, absence of the input protection resistor, or FTDI EEPROM missing the Rx invert bit)
* Incorrect COM port selected in RoverGauge. If the computer has more than one port available, be sure that you have the right one selected.
* Damaged/broken lines in the vehicle's wiring harness (or bad connection at the ECU main connector.)
* Plugged into incorrect connector in the vehicle. Be sure you're not connected to the Electronic Air Suspension (EAS) port.
