### ISSUE TITLE
Rovergauge 0.10.4-Windows-i686 - rovergauge.exe - System Error

### ISSUE THREAD

**Issue by gecko951** [colinbourassa/rovergauge#20]
Updated Windows 10 32-bit with Rovergauge 0.10.4-Windows-i686 and get the following error when trying to run the program: 

rovergauge.exe - System Error
The code execution cannot proceed because libwinpthread-1.dll was not found. Reinstalling the program may fix this problem.

I tried extracting the zip again to a different directory and got the same error when running rovergauge.exe

Rovergauge 0.10.3 works OK on the same system.

**Comment by colinbourassa** [comment]
Thanks for the report. This was due to a change in dependencies in the MXE cross environment that I use to create Windows builds. I've updated the build script to pull in the missing DLL.

Fixed in 0.10.5.
