### ISSUE TITLE
file missing for Linux/debian code

### ISSUE THREAD

**Issue by CGFlyer85** [colinbourassa/rovergauge#22]
Hi, first of all, thanks for this awsome piece of software !
Second, I'm french so sorry for my english...

I'm curently working on various TVR (Griffith, Chimaera and Tasmin) all equiped with a 14CUX ecu, I've used RG before and discovered I could install it on my raspberry.

But, when trying to complile the code "_make_" I'm returned with a missing file : "comm14cux.h"

I've search the whole github witout result... Is it just a mistake that it is not included in the archive ? Or am'I missing some step ?

Thanks in advance for your precious help !!

**Comment by colinbourassa** [comment]
Thanks very much -- I'm glad you like the software.

You'll need to build and install [libcomm14cux](https://github.com/colinbourassa/libcomm14cux) before building RoverGauge. libcomm14cux is the back-end library that actually talks to the 14CUX ECU over the serial port.

After building libcomm14cux (using CMake), run "make install" to install the library and comm14cux.h to the system directory (which will be under /usr/local or /usr).

**Comment by CGFlyer85** [comment]
Hi, thanks for your help.
Well, the installation goes wel, but I end up with a 512kio executable, wich does nothing, I've instaled QT5 before, but do I need to do something special with it ?

Sorry, I'm quite a noob with raspberry, way more at ease with a carburetor in hand ^^'

Thanks again.

**Comment by colinbourassa** [comment]
If libcomm14cux got installed to ```/usr/local/lib```, then you probably just need to update the system library cache. You can do that by running ```sudo ldconfig``` and then try running RoverGauge again. If that doesn't work, first confirm that libcomm14cux is actually installed to ```/usr/local/lib```:
~~~
ls /usr/local/lib/libcomm14cux.*
~~~
...and then try temporarily changing the library search path and running RoverGauge: 
~~~
export LD_LIBRARY_PATH=/usr/local/lib
./rovergauge
~~~

**Comment by CGFlyer85** [comment]
Yay ! Made it work by re-instaling everything in the right place, and updating cache. Will see next week if I can connect to my car.
Thanks again !
